moviewebsite/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path("register/",views.register,name="register"),
    path("login/",views.login_user,name="login"),
    path("logout/",views.logout_user,name="logout")


]

moviewebsite/moviewebsite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from moviewebsite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('movieapp.urls')),
    path('accounts/',include('accounts.urls'))
    # path('', include('django.contrib.auth.urls')),
    # path('credentials/',include('credentials.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviewebsite/templates/add_movies.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">{{controller}}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}

                <input type="submit" value ="{{controller}}" class="btn btn-danger">
            </form>
<!--            <div class="container">-->
<!--                <h1>{{ controller }}</h1>-->
<!--                <form method="POST" enctype="multipart/form-data">-->
<!--                    {% csrf_token %}-->
<!--                    {{ form.as_p }}-->
<!--                    <button type="submit">Save</button>-->
<!--                </form>-->
            </div>
        </div>
    </div>
</div>

{% endblock %}

moviewebsite/templates/base.html
<!doctype html>
{% load static %}



<!--
            </center>
        </div>
    </div>
</div>

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
<!-- <link rel="stylesheet" href="{% static 'css/custom.css' %}">-->
<!--    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" >-->
<!--    <script src="https://kit.fontawesome.com/863d75cd0e.js" crossorigin="anonymous"></script>-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <div class="container-fluid">
        <div class="header">
            <center>
            </center>
            </div>
        </div>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Movie Review</title>
<style>
      body{
      background-color:#151313;

      }
      #backdrop{
      background-color:#FEF9E7;





      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}">Movie Writer</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'add_movies' %}">Add Movies</a>
        </li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbar_Dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
        Categories
    </a>
    <div class="dropdown-menu" aria-labelledby="navbar_Dropdown">

          <form method="get" id="categoryForm" class="px-4 py-3">
              <select name="category" class="form-control" onchange="document.getElementById('categoryForm').submit();">
                  <option value="">All Categories</option>

                  {% for category in categories %}
                  <option value="{{ category.name }}">{{ category.name }}</option>

                  {% endfor %}
              </select>
          </form>
    </div>
        {% if user.is_authenticated %}

<!--        <button type="submit">Filter</button>-->


<!--        <li class="nav-item dropdown">-->
<!--          <a class="nav-link dropdown-toggle" href="#" id="navbar_Dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--            Category-->
<!--            {{category}}-->
<!--          </a>-->

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </li>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{user.username}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
<!--            <li><a class="dropdown-item" href="#">Action</a></li>-->
<!--            <li><a class="dropdown-item" href="#">Another action</a></li>-->
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
        </li>
        {% endif %}
<!--        <li class="nav-item">-->
<!--          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
<!--        </li>-->
      </ul>
      <form class="d-flex" method="GET" action="{% url 'index'%}">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="title">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
    <br>
    <div style="text-align: center;">
<img src="{% static 'img/logo_movie.png' %}" alt="logimage" width="130px;" height="130px;" center>
    </div>
    <br>
<!--&lt;!&ndash;    <div class="container mt-5">&ndash;&gt;-->
<!--        <h1>{{category_name}} Movies</h1>-->
<!--        <ul>-->
<!--            {% for movie in movies %}-->
<!--            <li>-->
<!--                <a href="{% url 'details' id=movie.id %}">{{ movie.title }}</a>-->
<!--&lt;!&ndash;                ({{ movie.category.name }})&ndash;&gt;-->
<!--            </li>-->
<!--            {% endfor %}-->
<!--        </ul>-->

    </div>

    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <img class="my_image my_image_padding" src="{% static 'img/movie_banner.png' %}" alt="movie_writer" width="1920px" height="240px" style="border-radius: 20px; padding-left: 50px;padding-right:50px";>


    <h1></h1>



    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
    <br>
    <section></section>
  <div>

      <div class ="container">
    <div class="container-fluid">
        <div class = "footer navbar-fixed-bottom my_footer">
            <p class="text-center" style="background-color:#orange; height:60px;padding-top:20px;font-size:14px;color:white;border-radius: 10px">&copy;  pvt ltd. All rights Reserve</p>
            </div>
        </div>
    </div>
</div>
  </section>
  <script src="{% static 'js/popper.min.js' %}" ></script>
<script src="{% static 'js/bootstrap.min.js' %}" ></script>
  </body>
</html>

moviewebsite/templates/category.html
{% extends 'base.html' %}


{% block content %}

<div>
    <div class="row my_row_class">
        <div class = "mx-auto">
        <p style="letter-spacing :.2em;font-size:14px;text-transform:uppercase;font-style:verdana;text-center;"><a href="{% url 'index' %}">{{category_name}}</a></p>
    </div>
        </div>
</div>
{% endif %}

<div class="mx_auto">
    {% if category %}
</div>
<br>
<div>
    <h1 class="text-center my_title" style="letter-spacing :.2em;font-size:14px;text-transform:uppercase;font-style:verdana;">{{category.name}} </h1>
</div>
{% else %}
<div>
</div>
<br>
<div>
    <h1 class="text-center my_title" style="font-family:cambria;padding:15px;">{{category_name}}</h1>

{% endif %}

<div class="container">
    <div class="row mx_auto">
        {% for category in categories %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 xol-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <div>
                    <a href="{{movie.id}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}} width=1250px height=50px"></a>
                    <div class="card-body">
                        <h4 style="font-family:cambria;text-tranform:uppercase;letter-spacing:.2em;padding-tp:15px;padding-bottom:10px;">{{product.name}}</h4>
                        <p style="font-family:cambria;text-tranform:uppercase;letter-spacing:.2em;padding-tp:15px;padding-bottom:10px;">{{product.price}}</p>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm{% if products.number == pg %} active {% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
    <br>
</div>


{% endblock %}

{% endblock %}

moviewebsite/templates/details.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="card" >
        <div class="card-body">
        <div class="row">
            <div class="col-md-4">
                <img src="{{movie.image}}" alt="{{movie.title}}" class="img-fluid" width="75%">
            </div>
            <div class="col-md-8">
                <h3 class="text-center">{{movie.title}}</h3>
                <br>
                <p>{{movie.description}}</p>
                <h5>Cast:{{movie.actors}}</h5>
                <h5>Rating:{{average}}/10</h5>

                {% if request.user.is_authenticated %}
                {% if request.user.is_superuser %}
                <a href="{% url 'edit' movie.id %}" class="btn btn-warning">Edit</a>
                <a href="{% url 'delete' movie.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this?')";>Delete</a>
                {% endif %}
                {% endif %}
        </div>
    </div>
        </div>
</div>
    <br>
    <div class="card">
        <div class="card-body">
             <h3 class="text-center">Add Review</h3>
            <form action="{% url 'add_review' movie.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>
                <br>
                <label for="rating">Rating</label>
                <input type="range" id="rangeInput"
                name="rating" min="0" max="10" value="0"  step="0.5"
                       oninput="amount.value=rangeInput.value">

                <output name="amount" id="amount" for="rangeInput">0</output>
                <br>
                <br>
                <input type="submit"  class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
            <div class="card" style="background-color:#f5eeee;">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5 class="text-left">{{review.user.username}}</h5>
                            <h5>{{review.rating}}</h5>
                            {% if request.user == review.user %}
                            <a href="{% url 'edit_review' movie.id review.id %}">Edit</a>
                            <a href="{% url 'delete_review' movie.id review.id %}" onclick="return confirm('Are you sure you want to delete this?')";>Delete</a>
                            {% endif %}
                        </div>
                        <div class="col-md-9">
                            <p>{{review.comment}}</p>
                        </div>
                    </div>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

moviewebsite/templates/edit_review.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                {% if error %}
                <strong style="color:red;">{{ error}}</strong>
                {% endif %}

                <input type="submit" value ="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

moviewebsite/templates/index.html
{% extends 'base.html' %}
{% block content %}



<section class="wrapper">
    <div class="container-fostrap">
        <div>

            <h1 class="text-center" style="font-family:Arial narrow; color:#ff6900;font-weight: normal;">
    Top Movies
</h1>
        </div>
        <br>
        <div class="content">
            <div class="container" >
                <div class="row">
                    {% for movie in movies %}
                    <div class="col-md-4 col-sm-4">
                        <div class="card" id="backdrop" style="border-radius: 10px;">
                            <div class="img-card" style="display: block;margin-top: 10px;margin-bottom: 10px;margin-left: 10px;margin-right: 10px;">
                            <img src="{{movie.image}}"  width="75%" style="border-radius: 10px";>
                                <h3 class="text-center">{{movie.title}}</h3>
                                <li>{{movie.release_date}}</li>
                          </div>
                            <div class="card-content">
                                <h4 class="card-title">
                                </h4>
                            </div>
                            <div class="card-read-more text-centre">
                                <a href="{% url 'details' movie.id %}" class="btn btn-warning ">
                                    Read More
                                </a>
                                <br>

                            </div>
                        </div>
                    </div>

                    {% endfor %}

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</section>

{% endblock %}